# Spring properties
spring:
  application:
     name: cart-service  # Service registers under this name
  freemarker:
    enabled: false           # Ignore Eureka dashboard FreeMarker templates

# HTTP Server
server.port: 3333   # HTTP (Tomcat) port

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10   # DO NOT DO THIS IN PRODUCTION

management.endpoints.web.exposure.include: '*'