# Spring properties
spring:
  application:
     name: gateway-service  # Service registers under this name
  freemarker:
    enabled: false           # Ignore Eureka dashboard FreeMarker templates
  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 5s

# HTTP Server
server.port: 8080   # HTTP (Tomcat) port

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10   # DO NOT DO THIS IN PRODUCTION

management.endpoints.web.exposure.include: '*'